title: SmartLine
email: contato@smartlinepro.com.br
description: SmartLine website suporte
baseurl: ""
url: "http://suporte.smartlinepro.com.br"

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-feed
  - jekyll-redirect-from

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules

jekyll_admin:
  hidden_links:
    - posts

include: ['_pages', '_help']

